export const BLACK_COLOR = [
  'black',
  'black_90',
  'black_80',
  'black_70',
  'black_60',
  'black_50',
  'black_40',
  'black_30',
  'black_20',
  'black_10',
  'black_5',
] as const;

export const WHITE_COLOR = [
  'white',
  'white_90',
  'white_80',
  'white_70',
  'white_60',
  'white_50',
  'white_40',
  'white_30',
  'white_20',
  'white_10',
  'white_5',
] as const;

export const BLUE_COLOR = [
  'blue',
  'blue_dark_1',
  'blue_dark_2',
  'blue_light_1',
  'blue_light_2',
  'blue_90',
  'blue_80',
  'blue_70',
  'blue_60',
  'blue_50',
  'blue_40',
  'blue_30',
  'blue_20',
  'blue_10',
  'blue_5',
] as const;

export const ORANGE_COLOR = [
  'orange',
  'orange_dark_1',
  'orange_dark_2',
  'orange_light_1',
  'orange_light_2',
  'orange_90',
  'orange_80',
  'orange_70',
  'orange_60',
  'orange_50',
  'orange_40',
  'orange_30',
  'orange_20',
  'orange_10',
  'orange_5',
] as const;

export const PURPLE_COLOR = [
  'purple',
  'purple_dark_1',
  'purple_dark_2',
  'purple_light_1',
  'purple_light_2',
  'purple_90',
  'purple_80',
  'purple_70',
  'purple_60',
  'purple_50',
  'purple_40',
  'purple_30',
  'purple_20',
  'purple_10',
  'purple_5',
] as const;

export const RED_COLOR = [
  'red',
  'red_dark_1',
  'red_dark_2',
  'red_light_1',
  'red_light_2',
  'red_90',
  'red_80',
  'red_70',
  'red_60',
  'red_50',
  'red_40',
  'red_30',
  'red_20',
  'red_10',
  'red_5',
] as const;

export const YELLOW_COLOR = [
  'yellow',
  'yellow_dark_1',
  'yellow_dark_2',
  'yellow_light_1',
  'yellow_light_2',
  'yellow_90',
  'yellow_80',
  'yellow_70',
  'yellow_60',
  'yellow_50',
  'yellow_40',
  'yellow_30',
  'yellow_20',
  'yellow_10',
  'yellow_5',
] as const;

export const GREEN_COLOR = [
  'green',
  'green_dark_1',
  'green_dark_2',
  'green_light_1',
  'green_light_2',
  'green_90',
  'green_80',
  'green_70',
  'green_60',
  'green_50',
  'green_40',
  'green_30',
  'green_20',
  'green_10',
  'green_5',
] as const;

export const TEAL_BLUE_COLOR = [
  'teal_blue',
  'teal_blue_dark_1',
  'teal_blue_dark_2',
  'teal_blue_light_1',
  'teal_blue_light_2',
  'teal_blue_90',
  'teal_blue_80',
  'teal_blue_70',
  'teal_blue_60',
  'teal_blue_50',
  'teal_blue_40',
  'teal_blue_30',
  'teal_blue_20',
  'teal_blue_10',
  'teal_blue_5',
] as const;

export const PINK_COLOR = [
  'pink',
  'pink_dark_1',
  'pink_dark_2',
  'pink_light_1',
  'pink_light_2',
  'pink_90',
  'pink_80',
  'pink_70',
  'pink_60',
  'pink_50',
  'pink_40',
  'pink_30',
  'pink_20',
  'pink_10',
  'pink_5',
] as const;

export const BRONZE_COLOR = [
  'bronze',
  'bronze_dark_1',
  'bronze_dark_2',
  'bronze_light_1',
  'bronze_light_2',
  'bronze_90',
  'bronze_80',
  'bronze_70',
  'bronze_60',
  'bronze_50',
  'bronze_40',
  'bronze_30',
  'bronze_20',
  'bronze_10',
  'bronze_5',
] as const;

export const TIFFANY_COLOR = [
  'tiffany',
  'tiffany_dark_1',
  'tiffany_dark_2',
  'tiffany_light_1',
  'tiffany_light_2',
  'tiffany_90',
  'tiffany_80',
  'tiffany_70',
  'tiffany_60',
  'tiffany_50',
  'tiffany_40',
  'tiffany_30',
  'tiffany_20',
  'tiffany_10',
  'tiffany_5',
] as const;

export const GRAY_BLUE_COLOR = [
  'gray_blue_10',
  'gray_blue_15',
  'gray_blue_20',
  'gray_blue_25',
  'gray_blue_30',
  'gray_blue_35',
  'gray_blue_40',
  'gray_blue_45',
  'gray_blue_50',
  'gray_blue_55',
  'gray_blue_60',
  'gray_blue_65',
  'gray_blue_70',
  'gray_blue_75',
  'gray_blue_80',
  'gray_blue_85',
  'gray_blue_90',
  'gray_blue_91',
  'gray_blue_92',
  'gray_blue_93',
  'gray_blue_94',
  'gray_blue_95',
  'gray_blue_96',
  'gray_blue_97',
  'gray_blue_98',
  'gray_blue_99',
  'gray_blue_100',
] as const;
